<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_featured',
		'title' => 'Featured',
		'fields' => array (
			array (
				'key' => 'field_53d8b63265e09',
				'label' => 'featuredscreenshot',
				'name' => 'featuredscreenshot',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53cf752b7d08d',
				'label' => 'Quote',
				'name' => 'quote',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53d78eed77867',
				'label' => 'Frage',
				'name' => 'frage',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53d78b68710dc',
				'label' => 'Kunden',
				'name' => 'kunden',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_53fc944fc9cf0',
				'label' => 'Nutzentitel',
				'name' => 'nutzentitel',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fc929156f93',
				'label' => 'Frage1',
				'name' => 'frage1',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53fc92a456f94',
				'label' => 'Antwort1',
				'name' => 'antwort1',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53fc9731b57ef',
				'label' => 'Frage2',
				'name' => 'frage2',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53fc9741b57f0',
				'label' => 'Antwort2',
				'name' => 'antwort2',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53fc976900bfe',
				'label' => 'Frage3',
				'name' => 'frage3',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53fc977500bff',
				'label' => 'Antwort3',
				'name' => 'antwort3',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'featured',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}

?>
